// Generated by tools/gen_sprites.py. Do not edit by hand.

/// Sprite size in pixels. Drawn at half this in points, so that one
/// pixel lands on one pixel of a 2x display.
pub const SPRITE_W: usize = 44;
pub const SPRITE_H: usize = 40;

/// One bit per pixel, row-major, most significant bit first, 1 = ink.
pub static MASKS: &[(&str, &[&[u8]])] = &[
    ("cat", &[
        include_bytes!("../assets/animals/cat/cat_0.mask"),
        include_bytes!("../assets/animals/cat/cat_1.mask"),
        include_bytes!("../assets/animals/cat/cat_2.mask"),
        include_bytes!("../assets/animals/cat/cat_3.mask"),
        include_bytes!("../assets/animals/cat/cat_4.mask"),
        include_bytes!("../assets/animals/cat/cat_5.mask"),
        include_bytes!("../assets/animals/cat/cat_6.mask"),
        include_bytes!("../assets/animals/cat/cat_7.mask"),
    ]),
    ("dog", &[
        include_bytes!("../assets/animals/dog/dog_0.mask"),
        include_bytes!("../assets/animals/dog/dog_1.mask"),
        include_bytes!("../assets/animals/dog/dog_2.mask"),
        include_bytes!("../assets/animals/dog/dog_3.mask"),
        include_bytes!("../assets/animals/dog/dog_4.mask"),
        include_bytes!("../assets/animals/dog/dog_5.mask"),
        include_bytes!("../assets/animals/dog/dog_6.mask"),
        include_bytes!("../assets/animals/dog/dog_7.mask"),
    ]),
    ("rabbit", &[
        include_bytes!("../assets/animals/rabbit/rabbit_0.mask"),
        include_bytes!("../assets/animals/rabbit/rabbit_1.mask"),
        include_bytes!("../assets/animals/rabbit/rabbit_2.mask"),
        include_bytes!("../assets/animals/rabbit/rabbit_3.mask"),
        include_bytes!("../assets/animals/rabbit/rabbit_4.mask"),
        include_bytes!("../assets/animals/rabbit/rabbit_5.mask"),
        include_bytes!("../assets/animals/rabbit/rabbit_6.mask"),
        include_bytes!("../assets/animals/rabbit/rabbit_7.mask"),
    ]),
    ("squirrel", &[
        include_bytes!("../assets/animals/squirrel/squirrel_0.mask"),
        include_bytes!("../assets/animals/squirrel/squirrel_1.mask"),
        include_bytes!("../assets/animals/squirrel/squirrel_2.mask"),
        include_bytes!("../assets/animals/squirrel/squirrel_3.mask"),
        include_bytes!("../assets/animals/squirrel/squirrel_4.mask"),
        include_bytes!("../assets/animals/squirrel/squirrel_5.mask"),
        include_bytes!("../assets/animals/squirrel/squirrel_6.mask"),
        include_bytes!("../assets/animals/squirrel/squirrel_7.mask"),
    ]),
    ("elephant", &[
        include_bytes!("../assets/animals/elephant/elephant_0.mask"),
        include_bytes!("../assets/animals/elephant/elephant_1.mask"),
        include_bytes!("../assets/animals/elephant/elephant_2.mask"),
        include_bytes!("../assets/animals/elephant/elephant_3.mask"),
        include_bytes!("../assets/animals/elephant/elephant_4.mask"),
        include_bytes!("../assets/animals/elephant/elephant_5.mask"),
        include_bytes!("../assets/animals/elephant/elephant_6.mask"),
        include_bytes!("../assets/animals/elephant/elephant_7.mask"),
    ]),
    ("chicken", &[
        include_bytes!("../assets/animals/chicken/chicken_0.mask"),
        include_bytes!("../assets/animals/chicken/chicken_1.mask"),
        include_bytes!("../assets/animals/chicken/chicken_2.mask"),
        include_bytes!("../assets/animals/chicken/chicken_3.mask"),
        include_bytes!("../assets/animals/chicken/chicken_4.mask"),
        include_bytes!("../assets/animals/chicken/chicken_5.mask"),
        include_bytes!("../assets/animals/chicken/chicken_6.mask"),
        include_bytes!("../assets/animals/chicken/chicken_7.mask"),
    ]),
    ("rattlesnake", &[
        include_bytes!("../assets/animals/rattlesnake/rattlesnake_0.mask"),
        include_bytes!("../assets/animals/rattlesnake/rattlesnake_1.mask"),
        include_bytes!("../assets/animals/rattlesnake/rattlesnake_2.mask"),
        include_bytes!("../assets/animals/rattlesnake/rattlesnake_3.mask"),
        include_bytes!("../assets/animals/rattlesnake/rattlesnake_4.mask"),
        include_bytes!("../assets/animals/rattlesnake/rattlesnake_5.mask"),
        include_bytes!("../assets/animals/rattlesnake/rattlesnake_6.mask"),
        include_bytes!("../assets/animals/rattlesnake/rattlesnake_7.mask"),
    ]),
    ("meerkat", &[
        include_bytes!("../assets/animals/meerkat/meerkat_0.mask"),
        include_bytes!("../assets/animals/meerkat/meerkat_1.mask"),
        include_bytes!("../assets/animals/meerkat/meerkat_2.mask"),
        include_bytes!("../assets/animals/meerkat/meerkat_3.mask"),
        include_bytes!("../assets/animals/meerkat/meerkat_4.mask"),
        include_bytes!("../assets/animals/meerkat/meerkat_5.mask"),
        include_bytes!("../assets/animals/meerkat/meerkat_6.mask"),
        include_bytes!("../assets/animals/meerkat/meerkat_7.mask"),
    ]),
    ("giraffe", &[
        include_bytes!("../assets/animals/giraffe/giraffe_0.mask"),
        include_bytes!("../assets/animals/giraffe/giraffe_1.mask"),
        include_bytes!("../assets/animals/giraffe/giraffe_2.mask"),
        include_bytes!("../assets/animals/giraffe/giraffe_3.mask"),
        include_bytes!("../assets/animals/giraffe/giraffe_4.mask"),
        include_bytes!("../assets/animals/giraffe/giraffe_5.mask"),
        include_bytes!("../assets/animals/giraffe/giraffe_6.mask"),
        include_bytes!("../assets/animals/giraffe/giraffe_7.mask"),
    ]),
];

pub const COFFEE_W: usize = 28;
pub const COFFEE_H: usize = 28;

/// The cup on the menu row that asks for one.
pub static COFFEE: &[u8] = include_bytes!("../assets/ui/coffee.mask");
